momooz/momooz/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # path('admins/', admin.site.urls),
    path('admin/', include('momoozAdmin.urls')),
    path('superadmin/', admin.site.urls),
    path('', include('momoozUser.urls')),
]


urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

momooz/momoozAdmin/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.login, name='login'),
    path('forgot-password/',views.forgot_password, name='forgot_password'),
    path('logout',views.logout, name='logout'),
    path('home/',views.index, name='index'),
    path('roles',views.roles, name='roles'),
    path('add_roles',views.add_roles, name='add_roles'),
    path('edit_role/<int:pk>',views.edit_role, name='edit_role'),
    path('delete_role/<int:pk>',views.delete_role, name='delete_role'),
    path('set_permission/<int:pk>',views.set_permission, name='set_permission'),
    
    path('add_sub_path',views.add_sub_path, name='add_sub_path'),
    path('add_main_path',views.add_main_path, name='add_main_path'),
    path('path',views.path, name='path'),
    path('Region/',views.Region, name='Region'),
    path('Region/addRegion/',views.addRegion, name='addRegion'),
    path('Region/disableRegion/',views.disableRegion, name='disableRegion'),
    path('Region/editRegion/<str:pk>/',views.editRegion, name='editRegion'),
    path('Region/pincode/<str:pk>/',views.pincode, name='pincode'),
    path('Region/pincode/addPincode',views.addPincode, name='addPincode'),
    path('Region/pincode/disablePincode',views.disablePincode, name='disablePincode'),
    # admins
    path('add_admin',views.add_admin, name='add_admin'),
    path('admins',views.admins, name='admins'),
    path('edit_admins/<int:pk>',views.edit_admins, name='edit_admins'),
    path('view_admins/<int:pk>',views.view_admins, name='view_admins'),
    path('disable_admin',views.disable_admin, name='disable_admin'),
    path('change_password/<int:pk>',views.change_password, name='change_password'),
    # path('momoozAdmin',views.momoozAdmin, name='momoozAdmin'),
    # banners
    path('Banner/',views.Banner, name='Banner'),
    path('Banner/addBanner/',views.addBanner, name='addBanner'),
    path('Banner/disableBanner',views.disableBanner, name='disableBanner'),
    path('Banner/editBanner/<str:pk>',views.editBanner, name='editBanner'),
    # offers
    path('offers',views.offers, name='offers'),
    path('add_offers',views.add_offers, name='add_offers'),
    path('edit_offers/<int:pk>',views.edit_offers, name='edit_offers'),
    path('delete_offers',views.delete_offers, name='delete_offers'),
    path('add-product-to-offers/',views.add_product_to_offers, name='add_product_to_offers'),
    path('SalesReport',views.SalesReport, name='SalesReport'),
    #inventry
    path('Inventory/',views.CategoryView, name='CategoryView1'),
    path('Inventory/CategoryView',views.CategoryView, name='CategoryView'),
    path('Inventory/CategoryView/addCategory',views.addCategory, name='addCategory'),
    path('Inventory/CategoryView/disableCategory',views.disableCategory, name='disableCategory'),
    path('Inventory/CategoryView/editCategory/<str:pk>/',views.editCategory, name='editCategory'),
    path('Inventory/Varient',views.Varient, name='Varient'),
    path('Inventory/Varient/addVarient',views.addVarient, name='addVarient'),
    path('Inventory/Varient/disableVarient',views.disableVarient, name='disableVarient'),
    path('Inventory/Varient/addValues/<str:pk>',views.addValues, name='addValues'),
    path('Inventory/Varient/editVarient/<str:pk>',views.editVarient, name='editVarient'),
    path('Inventory/Varient/editVarient/<str:pk/disableVarientValues',views.disableVarientValues, name='disableVarientValues'),
    path('Inventory/Varient/ViewValues',views.ViewValues, name='ViewValues'),
    path('Inventory/ProductView/',views.ProductView, name='ProductView'),
    path('Inventory/ProductView/add_ProductView',views.add_ProductView, name='add_ProductView'),
    path('Inventory/ProductView/disableProduct',views.disableProduct, name='disableProduct'),
    path('Inventory/ProductView/viewProduct/<str:pk>/',views.viewProduct, name='viewProduct'),
    path('Inventory/ProductView/viewProduct/editProductVarient/<str:pk>/',views.editProductVarient, name='editProductVarient'),
    path('Inventory/ProductView/viewProduct/addItems/<str:pk>/',views.addItems, name='addItems'),
    path('Inventory/ProductView/editProduct/<str:pk>/',views.editProduct, name='editProduct'),
    path('Inventory/ProductView/disableProductItem',views.disableProductItem, name='disableProductItem'),
    path('Inventory/ProductView/disableProductItems',views.disableProductItems, name='disableProductItems'),
    path('Inventory/itemsList/',views.itemsList, name='itemsList'),
    path('upload_thumnails/',views.upload_thumnails, name='upload_thumnails'),
    path('Thumbnail_remove/',views.Thumbnail_remove, name='Thumbnail_remove'),
    #ajax
    path('Display_Order/',views.Display_Order, name='Display_Order'),
    path('varientSelect/',views.varientSelect, name='varientSelect'),
    path('Display_Order_Varient/',views.Display_Order_Varient, name='Display_Order_Varient'),
    path('VarientName_Check/',views.VarientName_Check, name='VarientName_Check'),
    path('Banner_Display_Order/',views.Banner_Display_Order, name='Banner_Display_Order'),
    path('search_admin/',views.search_admin, name='search_admin'),
    # path('CustomerReport',views.CustomerReport, name='CustomerReport'),
    # customers
    path('customers',views.customers, name='customers'),
    path('edit_customer/<str:pk>',views.edit_customer, name='edit_customer'),
    path('customers_disable',views.customers_disable, name='customers_disable'),
    path('customers_enable',views.customers_enable, name='customers_enable'),
    #contacts
    path('contacts',views.contacts, name='contacts'),
    # orders
    path('orders',views.orders, name='orders'),
    path('new_orders',views.new_orders, name='new_orders'),
    # coupons
    path('add_coupon',views.add_coupon, name='add_coupon'),
    path('edit_coupons/<int:pk>',views.edit_coupons, name='edit_coupons'),
    path('coupons',views.coupons, name='coupons'),
    path('coupon_code_users',views.coupon_code_users, name='coupon_code_users'),
    path('delete_coupons/<int:pk>',views.delete_coupons, name='delete_coupons'),
    # brands
    path('brands',views.brands, name='brands'),
    path('add_brand',views.add_brand, name='add_brand'),
    path('delete_brand',views.delete_brand, name='delete_brand'),
    path('edit_brand/<int:pk>',views.edit_brand, name='edit_brand'),
    # 404
    path('page_not_found',views.page_not_found, name='page_not_found'),
    # log
    path('admin_log',views.admin_log, name='admin_log'),
    path('export_csv/',views.export_csv, name='export_csv'),
    path('bulkStocks/',views.bulkStocks, name='bulkStocks'),
    path('notifications/',views.notifications, name='notifications'),
    path('add_notifications/',views.add_notifications, name='add_notifications'),
    path('send_notification/<int:pk>',views.send_notification, name='send_notification'),
    path('delete_notification/<int:pk>',views.delete_notification, name='delete_notification'),
    path('User_log/',views.User_log, name='User_log'),
    #reports
    path('Order_report/',views.Order_report, name='Order_report'),
    path('Customer_report/',views.Customer_report, name='Customer_report'),
    path('generateReportCSV/',views.generateReportCSV, name='generateReportCSV'),
    path('render_to_pdf',views.render_to_pdf),
    path('Print_invoice/<int:pk>', views.Print_invoice, name="Print_invoice"),
    # contact
    path('disappear_msg_render/<int:pk>', views.disappear_msg_render, name="disappear_msg_render"),
]

handler404 = 'momoozAdmin.views.page_not_found'

    
 

momooz/momoozUser/models.py
from email.policy import default
from django.db import models
from momoozAdmin.models import *

# Create your models here.

class WishListTable(models.Model):
    Product_id = models.ForeignKey(Product,on_delete=models.CASCADE)
    WishlistUser = models.ForeignKey(Customer,on_delete=models.CASCADE,blank=True,null=True)
    added_date = models.DateTimeField(auto_now_add=True)
    class Meta:
        db_table = "Wishlist"

class Total_Cart_Table(models.Model):
    Customer_id = models.ForeignKey(Customer,on_delete=models.CASCADE)
    Total_Price = models.DecimalField(max_digits=12,decimal_places=2)
    Total_Offer_Price = models.DecimalField(max_digits=12,decimal_places=2)
    Total_Final_Price = models.DecimalField(max_digits=12,decimal_places=2)
    Total_Quantity = models.PositiveIntegerField()
    created = models.DateTimeField(auto_now=True, verbose_name='created')
    class Meta:
        db_table="Total_cart"


class CartTable(models.Model):
    Customer_id = models.ForeignKey(Customer,on_delete=models.CASCADE)
    cart_quantity = models.PositiveIntegerField(default=1,blank=True)
    Cart_Price = models.DecimalField(max_digits=12,decimal_places=2,null=True)
    Cart_offer_price = models.DecimalField(max_digits=12,decimal_places=2,null=True)
    Cart_Total_Price = models.DecimalField(max_digits=12,decimal_places=2,null=True)
    product_id = models.ForeignKey(Product_Varients,on_delete=models.CASCADE)
    available = models.BooleanField(default=True, verbose_name="available")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, verbose_name='updated')
    
    class Meta:
        db_table = 'Cart_table'


class UserLog(models.Model):
    
    Action = models.CharField(max_length=500,blank=True)
    Date = models.CharField(max_length=500,blank=True)
    User = models.CharField(max_length=255,blank=True)

    class Meta:
        db_table = 'User_Log'

class Contact_us(models.Model):

    
    name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False,blank=True)

momooz/momoozAdmin/templates/Inventory/Products/addItems.html
{% extends 'main.html' %}
{% block title%} Add Items {% endblock title%}
{% block contents %}
<div class="col-md-12 col-sm-12 col-xl-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-sm-4">
                    <div class="ml-auto">
                        <h3 class="card-title">Add Items</h3>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            <form method="post" action="{% url 'addItems' ProId %}">{% csrf_token %}
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="exampleInputUsername1">{{form.Varient_name.label}}</label>
                            {{form.Varient_name}}
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">{{form.Selling_Prize.label}}</label>
                            {{form.Selling_Prize}}
                        </div>
                        <div class="form-group">
                            <label for="exampleInputUsername1">{{form.Product_Offers.label}}</label>
                            {{form.Product_Offers}}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="exampleInputUsername1">{{form.Varient_Values.label}}</label>
                            <select name="Varient_Values" class="form-control form-control-sm" required="" id="id_Varient_Values">
                                <option value="" selected="">select</option>
                                {% for i in VarValues %}
                                <option value="1">{{i}}</option>
                                {% endfor %}
                              </select>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">{{form.Display_Prize.label}}</label>
                            {{form.Display_Prize}}
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">{{form.Product_stock.label}}</label>
                            {{form.Product_stock}}
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">{{form.status.label}}</label>
                            {{form.status}}
                        </div>

                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label for="exampleInputEmail1">{{form.Description.label}}</label>
                            {{form.Description}}
                        </div>
                    </div>
                </div>
                <br>
                <div class="col-sm-12" style="text-align: center;">
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <a href="{% url 'Varient' %}" class="btn btn-light">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>




{% endblock contents %}

momooz/momoozAdmin/templates/Inventory/Products/addProduct.html
{% extends 'main.html' %}
{% block title%} Add Products {% endblock title%}
{% block contents %}
<div class="col-md-12 col-sm-12 col-xl-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-sm-4">
                    <div class="ml-auto">
                        <h3 class="card-title">Add Product</h3> 
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            <form method="post" action="{% url 'add_ProductView' %}" enctype="multipart/form-data">{% csrf_token %}
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="exampleInputUsername1">{{form.Name.label}}</label>
                            {{form.Name}}
                        </div>
                        <div class="form-group">
                            <label for="exampleInputUsername1">{{form.Thumbnail_image.label}}</label><span style="font-size: smaller;font-style: italic;color: crimson;"> (Upload an image above 1000*1000px size)</span>
                            {{form.Thumbnail_image}}
                        </div>
                        <div class="form-group">
                            <label for="exampleInputUsername1">Varient Type</label>
                            <select name="Varient_Type" class="form-control form-control-sm" required=""
                                id="id_Varient_Type">
                                <option value="" selected="">Select</option>
                                {% for i in Types %}
                                <option value="{{i.id}}">{{i}}</option>
                                {% endfor %}
                            </select>
                        </div>

                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="exampleInputEmail1">{{form.Product_Category.label}}</label>
                            <select name="Product_Category" class="form-control form-control-sm" required="" id="id_Product_Category">
                                <option value="" selected="">Select</option>
                                {% for cat in Categories %}
                                <option value="{{cat.id}}">{{cat}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">{{form.Product_Brand.label}}</label>
                            <select name="Product_Brand" class="form-control form-control-sm" required="" id="id_Product_Brand">
                                <option value="" selected="">Select</option>
                                {% for brand in Brands %}
                                <option value="{{brand.id}}">{{brand}}</option>
                                {% endfor %}
                              </select>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">{{form.status.label}}</label>
                            <select name="Status" class="form-control form-control-sm" id="id_status" disabled>
                                <option value="">{{form.status.value}}</option>
                            </select>
                            {{form.status.as_hidden}}
                            {{form.Product_Items.as_hidden}}
                        </div>

                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label for="exampleInputEmail1">{{form.Description.label}}</label>
                            {{form.Description}}
                        </div>
                    </div>
                </div>
                <hr>
                <div class="card" id="VarientElement" style="display: none;">
                    <div class="card-header" >
                        <div class="row ">
                            <div class="col-sm-4">
                                <div class="ml-auto">
                                    <h3 class="card-title">Varients</h3>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row varient">
                            <div class="col-lg-10 row" id="varientId">
                                <div class="form-group col-3">
                                    <label for="exampleInputUsername1">{{form_1.Varient_name.label}}</label>
                                    <input type="text" name="Varient_name[]" maxlength="255" class="form-control form-control-sm" required="" id="id_Varient_name">
                                </div>
                                <div class="form-group col-3">
                                    <label for="exampleInputUsername1" class="varient_Values1"></label>
                                    <select name="Varient_Values[]" class="form-control form-control-sm VarientSelect"
                                        required="" id="id_Varient_Values">
                                    </select>
                                </div>
                                <div class="form-group col-2">
                                    <label for="exampleInputUsername1">{{form_1.Selling_Prize.label}}</label>
                                    <input type="text" name="Selling_Prize[]" maxlength="255" class="form-control form-control-sm" required="" id="id_Selling_Prize">
                                </div>
                                <div class="form-group col-2">
                                    <label for="exampleInputUsername1">{{form_1.Display_Prize.label}}</label>
                                    <input type="text" name="Display_Prize[]" maxlength="255" class="form-control form-control-sm" required="" id="id_Display_Prize">
                                </div>
                                <div class="form-group col-2">
                                    <label for="exampleInputUsername1">{{form_1.Product_stock.label}}</label>
                                    <input type="number" name="Product_stock[]" class="form-control form-control-sm" required>
                                </div>
                            </div>
                            <div class="col-lg-2">
                                <div class="form-group" style="text-align: center;padding-top: 1.3em;" id="but">
                                    <button class="btn btn-link plus-varient-set-type-btn" type="button"
                                        style="margin: 0 auto;padding-top: 8%;"><i class="fas fa-plus-square"
                                            style="font-size: large;"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <div class="col-sm-12" style="text-align: center;">
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <a href="{% url 'ProductView' %}" class="btn btn-light">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="http://139.59.91.27/dev2/dnb/assets/js/jquery.min.js" type="text/javascript"></script>
<script>
    $(document).on('click', '.plus-varient-set-type-btn', function () {
        var htm1 = $('#varientId').html();
        var minus = '<div class="col-lg-2">\
                <div class="form-group" style="text-align: center;padding-top: 1.3em;" id="but">\
                <button class="btn btn-link minus-varient-btn" type="button"\
                style="margin: 0 auto;padding-top: 8%;"><i class="fa fa-minus"\
                style="font-size: large;"></i></button>\
                </div>\
                </div>'
        var tags = '<div class="row varient" ><div class="col-lg-10 row" id="varientId">' + htm1 + '</div>' + minus + '</div>'
        $('.varient:first').after(tags);
    })
    $(document).on('click', '.minus-varient-btn', function () {
        $(this).parent().parent().parent().remove();
    })


</script>

<script>
    $("#id_Varient_Type").change(function () {
        var typeId = $(this).val();
        if (typeId) {
            $("#VarientElement").show(500)
            $.ajax({
                type: "POST",
                url: '{% url "varientSelect" %}',
                data: {
                    'subject_id': typeId,
                    'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                },
                success: (data) => {
                    console.log(data.Type)
                    let html_data = '<option value=0>None</option>';
                    data.values.forEach(function (data) {
                        html_data += `<option value="${data.id}">${data.Varient_Values}</option>`
                    });
                    $(".VarientSelect").html(html_data);
                    $('.varient_Values1').html('<p>' + data.Type + '</p>')
                }
            })
        }
        else{
            $("#VarientElement").hide(500)
        }
    })
</script>

<script>

$('#id_Thumbnail_image').on('change', function () {
        var get_image = getSelectedFile('id_Thumbnail_image')
        isGoodImage(get_image, 1000, 1000, 'id_Thumbnail_image');
    });


    var _URL = window.URL || window.webkitURL;
    function isSupportedBrowser() {
        return window.File && window.FileReader && window.FileList && window.Image;
    }

    function getSelectedFile(subjectId) {
        var fileInput = document.getElementById(subjectId);
        var fileIsSelected = fileInput && fileInput.files && fileInput.files[0];
        if (fileIsSelected)
            return fileInput.files[0];
        else
            return false;
    }

    function isGoodImage(file, cWidth, cHeight, subjectId) {
        var deferred = jQuery.Deferred();
        var Resolution
        var image = new Image();
        image.onload = function () {

            // Check if image is bad/invalid
            if (this.width + this.height === 0) {
                this.onerror();
                return;
            }

            // Check the image resolution
            if (parseInt(this.width) >= parseInt(cWidth) && parseInt(this.height) >= parseInt(cHeight)) {
                deferred.resolve(true);
            } else {
                deferred.resolve(false);
                alert('Image Resolution is not adaptable')
                document.getElementById(subjectId).value = ''
            }
        };

        image.onerror = function () {
            alert("Invalid image. Please select an image file.");
            deferred.resolve(false);
        }

        image.src = _URL.createObjectURL(file);

        return deferred.promise();
    }
</script>


{% endblock contents %}

momooz/momoozAdmin/templates/Inventory/Products/productVarient_edit.html
{% extends 'main.html' %}
{% block title%} Add Items {% endblock title%}
{% block contents %}
<div class="col-md-12 col-sm-12 col-xl-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-sm-4">
                    <div class="ml-auto">
                        <h3 class="card-title">Edit Items</h3>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            <form method="post" action="{% url 'editProductVarient' product_id %}">{% csrf_token %}
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="exampleInputUsername1">{{form.Varient_name.label}}</label>
                            {{form.Varient_name}}
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">{{form.Selling_Prize.label}}</label>
                            {{form.Selling_Prize}}
                        </div>
                        <div class="form-group">
                            <label for="exampleInputUsername1">{{form.Product_Offers.label}}</label>
                            {{form.Product_Offers}}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="exampleInputUsername1">{{form.Varient_Values.label}}</label>
                            {{form.Varient_Values}}
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">{{form.Display_Prize.label}}</label>
                            {{form.Display_Prize}}
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">{{form.Product_stock.label}}</label>
                            {{form.Product_stock}}
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">{{form.status.label}}</label>
                            {{form.status}}
                        </div>

                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label for="exampleInputEmail1">{{form.Description.label}}</label>
                            {{form.Description}}
                        </div>
                    </div>
                </div>
                <br>
                <div class="col-sm-12" style="text-align: center;">
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <a href="{% url 'viewProduct' product %}" class="btn btn-light">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="http://139.59.91.27/dev2/dnb/assets/js/jquery.min.js" type="text/javascript"></script>



{% endblock contents %}